[serverConfig]
    ip = "0.0.0.0"
    port = 25565
    networkCompressionThreshold = 256
    debug = true

[chunkEngine]
    async = true
    threadPerNewChunk = true
    maxThreads = 25

[bundledPlugins]
    dockyardCommands = true
    dockyardExtras = true
    mayaTestPlugin = true
    mudkipTestPlugin = true
    emberSeeker = false